DO $$ BEGIN CREATE TYPE user_role AS ENUM ('admin', 'stock_manager', 'lorry_manager', 'sales_staff', 'collector'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE sale_type AS ENUM ('cash', 'installment'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE payment_status AS ENUM ('pending', 'paid', 'overdue', 'defaulted', 'settled'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE inventory_txn_type AS ENUM ('purchase_in','sale_out','transfer_in','transfer_out','adjustment_add','adjustment_subtract','damaged','returned'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE collection_status AS ENUM ('pending','collected','missed','partial'); EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE TABLE IF NOT EXISTS roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL CHECK (name IN ('admin','stock_manager','lorry_manager','sales_staff','collector')), label text NOT NULL, description text, permissions jsonb DEFAULT '{}', created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
INSERT INTO roles (name, label, description) VALUES ('admin','Super Admin','Full system access'),('stock_manager','Stock Manager','Manage inventory'),('lorry_manager','Lorry Manager','Manage lorry'),('sales_staff','Sales Staff','POS operations'),('collector','Cash Collector','Field collection') ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text UNIQUE NOT NULL, name text NOT NULL, phone text, nic text, address text, photo_url text, role user_role NOT NULL DEFAULT 'sales_staff', is_active boolean DEFAULT true, lorry_id uuid, commission_rate numeric(5,4) DEFAULT 0.04, last_login_at timestamptz, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), deleted_at timestamptz);

CREATE TABLE IF NOT EXISTS categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text UNIQUE NOT NULL, description text, parent_id uuid REFERENCES categories(id) ON DELETE SET NULL, sort_order int DEFAULT 0, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS brands (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL, description text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text UNIQUE NOT NULL, barcode text UNIQUE, name text NOT NULL, description text, category_id uuid REFERENCES categories(id) ON DELETE SET NULL, brand_id uuid REFERENCES brands(id) ON DELETE SET NULL, image_url text, cost_price int NOT NULL DEFAULT 0, cash_price int NOT NULL DEFAULT 0, installment_price int NOT NULL DEFAULT 0, warranty_months int DEFAULT 0, weight_kg numeric(10,3), is_active boolean DEFAULT true, low_stock_threshold int DEFAULT 10, has_serial boolean DEFAULT false, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), deleted_at timestamptz);
CREATE TABLE IF NOT EXISTS product_serials (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_id uuid REFERENCES products(id) ON DELETE CASCADE, serial_number text NOT NULL, sale_id uuid, status text DEFAULT 'in_stock' CHECK (status IN ('in_stock','sold','returned','damaged')), warranty_end_date date, created_at timestamptz DEFAULT now());

CREATE TABLE IF NOT EXISTS warehouses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, code text UNIQUE NOT NULL, address text, phone text, manager_id uuid REFERENCES users(id) ON DELETE SET NULL, is_active boolean DEFAULT true, created_at timestamptz DEFAULT now());
INSERT INTO warehouses (name, code, address) VALUES ('Main Warehouse','WH-MAIN','Head Office') ON CONFLICT (code) DO NOTHING;
CREATE TABLE IF NOT EXISTS inventory_warehouse (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), warehouse_id uuid REFERENCES warehouses(id) ON DELETE CASCADE, product_id uuid REFERENCES products(id) ON DELETE CASCADE, quantity int NOT NULL DEFAULT 0, reserved_quantity int DEFAULT 0, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), UNIQUE(warehouse_id, product_id));

CREATE TABLE IF NOT EXISTS lorries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text UNIQUE NOT NULL, plate_number text UNIQUE NOT NULL, name text NOT NULL, driver_name text, driver_phone text, current_location text, status text DEFAULT 'active' CHECK (status IN ('active','maintenance','inactive')), created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
INSERT INTO lorries (code, plate_number, name, driver_name) VALUES
('L01','WP-CAB-1234','Lorry 01','Driver'),('L02','WP-CAB-1235','Lorry 02','Driver'),
('L03','WP-CAB-1236','Lorry 03','Driver'),('L04','WP-CAB-1237','Lorry 04','Driver'),
('L05','WP-CAB-1238','Lorry 05','Driver'),('L06','WP-CAB-1239','Lorry 06','Driver'),
('L07','WP-CAB-1240','Lorry 07','Driver'),('L08','WP-CAB-1241','Lorry 08','Driver'),
('L09','WP-CAB-1242','Lorry 09','Driver'),('L10','WP-CAB-1243','Lorry 10','Driver'),
('L11','WP-CAB-1244','Lorry 11','Driver'),('L12','WP-CAB-1245','Lorry 12','Driver')
ON CONFLICT (code) DO NOTHING;
CREATE TABLE IF NOT EXISTS lorry_staff (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lorry_id uuid REFERENCES lorries(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id) ON DELETE CASCADE, assigned_date date NOT NULL DEFAULT CURRENT_DATE, is_active boolean DEFAULT true, UNIQUE(lorry_id, user_id, assigned_date));
CREATE TABLE IF NOT EXISTS inventory_lorry (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lorry_id uuid REFERENCES lorries(id) ON DELETE CASCADE, product_id uuid REFERENCES products(id) ON DELETE CASCADE, quantity int NOT NULL DEFAULT 0, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), UNIQUE(lorry_id, product_id));
CREATE TABLE IF NOT EXISTS lorry_routes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lorry_id uuid REFERENCES lorries(id) ON DELETE CASCADE, route_date date NOT NULL, route_name text, start_location text, end_location text, status text DEFAULT 'planned' CHECK (status IN ('planned','in_progress','completed')), notes text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS lorry_expenses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lorry_id uuid REFERENCES lorries(id) ON DELETE CASCADE, expense_type text NOT NULL, amount int NOT NULL, description text, expense_date date NOT NULL DEFAULT CURRENT_DATE, recorded_by uuid REFERENCES users(id) ON DELETE SET NULL, receipt_url text, created_at timestamptz DEFAULT now());

CREATE TABLE IF NOT EXISTS customers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, nic text UNIQUE, phone text NOT NULL, phone2 text, email text, address text NOT NULL, city text, gps_location text, guarantor_name text, guarantor_phone text, guarantor_nic text, photo_url text, nic_image_url text, signature_url text, credit_score int DEFAULT 100, status text DEFAULT 'active' CHECK (status IN ('active','blacklisted','defaulted','settled')), created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), deleted_at timestamptz);

CREATE TABLE IF NOT EXISTS installment_plans (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), plan_number text UNIQUE NOT NULL, customer_id uuid REFERENCES customers(id) ON DELETE RESTRICT, total_amount int NOT NULL, down_payment int NOT NULL DEFAULT 0, financed_amount int NOT NULL, interest_rate numeric(5,2) DEFAULT 0, interest_amount int DEFAULT 0, total_payable int NOT NULL, monthly_payment int NOT NULL, period_months int NOT NULL, start_date date NOT NULL, end_date date, status payment_status DEFAULT 'pending', staff_id uuid REFERENCES users(id) ON DELETE SET NULL, lorry_id uuid REFERENCES lorries(id) ON DELETE SET NULL, notes text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS installment_schedule (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), plan_id uuid REFERENCES installment_plans(id) ON DELETE CASCADE, installment_number int NOT NULL, due_date date NOT NULL, amount_due int NOT NULL, amount_paid int DEFAULT 0, payment_date date, status payment_status DEFAULT 'pending', penalty_amount int DEFAULT 0, notes text, created_at timestamptz DEFAULT now(), UNIQUE(plan_id, installment_number));
CREATE TABLE IF NOT EXISTS installment_payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), plan_id uuid REFERENCES installment_plans(id) ON DELETE RESTRICT, schedule_id uuid REFERENCES installment_schedule(id) ON DELETE SET NULL, amount int NOT NULL, payment_method text DEFAULT 'cash' CHECK (payment_method IN ('cash','bank_transfer','check')), receipt_number text, collected_by uuid REFERENCES users(id) ON DELETE SET NULL, payment_date timestamptz DEFAULT now(), notes text, created_at timestamptz DEFAULT now());

CREATE TABLE IF NOT EXISTS sales (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), invoice_number text UNIQUE NOT NULL, sale_type sale_type NOT NULL, customer_id uuid REFERENCES customers(id) ON DELETE SET NULL, lorry_id uuid REFERENCES lorries(id) ON DELETE SET NULL, warehouse_id uuid REFERENCES warehouses(id) ON DELETE SET NULL, staff_id uuid REFERENCES users(id) ON DELETE SET NULL, subtotal int NOT NULL, discount int DEFAULT 0, total int NOT NULL, payment_method text DEFAULT 'cash', installment_plan_id uuid REFERENCES installment_plans(id) ON DELETE SET NULL, status text DEFAULT 'completed' CHECK (status IN ('draft','completed','cancelled','returned')), notes text, sale_date timestamptz DEFAULT now(), created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS sale_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), sale_id uuid REFERENCES sales(id) ON DELETE CASCADE, product_id uuid REFERENCES products(id) ON DELETE RESTRICT, serial_id uuid REFERENCES product_serials(id) ON DELETE SET NULL, quantity int NOT NULL, unit_price int NOT NULL, total_price int NOT NULL, created_at timestamptz DEFAULT now());

CREATE TABLE IF NOT EXISTS collection_routes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), collector_id uuid REFERENCES users(id) ON DELETE RESTRICT, route_date date NOT NULL DEFAULT CURRENT_DATE, route_name text, target_area text, status text DEFAULT 'pending' CHECK (status IN ('pending','in_progress','completed')), total_planned int DEFAULT 0, total_collected int DEFAULT 0, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS collection_visits (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), route_id uuid REFERENCES collection_routes(id) ON DELETE CASCADE, installment_plan_id uuid REFERENCES installment_plans(id) ON DELETE RESTRICT, customer_id uuid REFERENCES customers(id) ON DELETE RESTRICT, amount_due int NOT NULL, amount_collected int DEFAULT 0, status collection_status DEFAULT 'pending', visit_time timestamptz, gps_location text, notes text, receipt_number text, created_at timestamptz DEFAULT now());

CREATE TABLE IF NOT EXISTS suppliers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, code text UNIQUE, contact_person text, phone text, email text, address text, is_active boolean DEFAULT true, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS purchase_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), po_number text UNIQUE NOT NULL, supplier_id uuid REFERENCES suppliers(id) ON DELETE RESTRICT, warehouse_id uuid REFERENCES warehouses(id) ON DELETE RESTRICT, order_date date NOT NULL DEFAULT CURRENT_DATE, expected_date date, status text DEFAULT 'draft' CHECK (status IN ('draft','submitted','approved','received','cancelled')), subtotal int DEFAULT 0, tax_amount int DEFAULT 0, total int DEFAULT 0, notes text, created_by uuid REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS purchase_order_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), po_id uuid REFERENCES purchase_orders(id) ON DELETE CASCADE, product_id uuid REFERENCES products(id) ON DELETE RESTRICT, quantity int NOT NULL, unit_cost int NOT NULL, total_cost int NOT NULL, received_quantity int DEFAULT 0, created_at timestamptz DEFAULT now());

CREATE TABLE IF NOT EXISTS inventory_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_id uuid REFERENCES products(id) ON DELETE RESTRICT, warehouse_id uuid REFERENCES warehouses(id) ON DELETE SET NULL, lorry_id uuid REFERENCES lorries(id) ON DELETE SET NULL, txn_type inventory_txn_type NOT NULL, reference_type text, reference_id uuid, quantity int NOT NULL, previous_quantity int NOT NULL, new_quantity int NOT NULL, unit_cost int, total_cost int, performed_by uuid REFERENCES users(id) ON DELETE SET NULL, notes text, created_at timestamptz DEFAULT now());

CREATE TABLE IF NOT EXISTS expenses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), expense_type text NOT NULL, category text, amount int NOT NULL, description text, expense_date date NOT NULL DEFAULT CURRENT_DATE, recorded_by uuid REFERENCES users(id) ON DELETE SET NULL, receipt_url text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS commissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), staff_id uuid REFERENCES users(id) ON DELETE RESTRICT, sale_id uuid REFERENCES sales(id) ON DELETE SET NULL, commission_amount int NOT NULL, commission_rate numeric(5,4) NOT NULL, sale_amount int NOT NULL, status text DEFAULT 'pending' CHECK (status IN ('pending','approved','paid')), paid_date date, notes text, created_at timestamptz DEFAULT now());

CREATE TABLE IF NOT EXISTS settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key text UNIQUE NOT NULL, value jsonb NOT NULL DEFAULT '{}', description text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
INSERT INTO settings (key, value, description) VALUES
('company_name','"Sujee Enterprises"','Company name'),
('company_address','"Head Office, Sri Lanka"','Address'),
('currency','"LKR"','Currency'),
('default_commission_rate','0.04','Default commission'),
('low_stock_threshold','10','Low stock'),
('penalty_rate_monthly','0.02','Penalty rate'),
('vat_rate','0.00','VAT')
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE SET NULL, action text NOT NULL, entity_type text, entity_id uuid, old_values jsonb, new_values jsonb, ip_address text, user_agent text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, type text NOT NULL, title text NOT NULL, message text NOT NULL, data jsonb DEFAULT '{}', is_read boolean DEFAULT false, created_at timestamptz DEFAULT now());

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_products_code ON products(code);
CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode);
CREATE INDEX IF NOT EXISTS idx_customers_nic ON customers(nic);
CREATE INDEX IF NOT EXISTS idx_installment_plans_customer ON installment_plans(customer_id);
CREATE INDEX IF NOT EXISTS idx_sales_staff ON sales(staff_id);
CREATE INDEX IF NOT EXISTS idx_sales_sale_date ON sales(sale_date);